baseURL = "https://byrnet.github.io/dg.wr.io"
languageCode = "en-us"
title = "Your Site Title"
theme = "hugo-theme-cleanwhite"
relativeURLs = false
disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
    guessSyntax = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]