baseURL = "https://byrnet.github.io/dg.wr.io"
languageCode = "en-us"
title = "Alex's Digital Garden"
theme = "hugo-theme-cleanwhite"

[params]
  description = "Personal knowledge management experiment"
  sidebar_about_description = "Business process optimizer"